// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UNAHUR.IoT.DAL.MOdels;

[Table("CatalogItems", Schema = "common")]
public partial class CatalogItem
{
    /// <summary>
    /// Unique identifier
    /// </summary>
    [Key]
    public long CatalogItemId { get; set; }

    /// <summary>
    /// Partition ID
    /// </summary>
    public int PartitionId { get; set; }

    /// <summary>
    /// Nombre para mostrar
    /// </summary>
    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    /// <summary>
    /// descripcion larga
    /// </summary>
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    /// <summary>
    /// Fecha de ultima modificacion
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime LastModified { get; set; }

    /// <summary>
    /// Usuario de ultima modificacion
    /// </summary>
    [Required]
    [StringLength(128)]
    [Unicode(false)]
    public string LastModifiedBy { get; set; }

    [ForeignKey("PartitionId")]
    [InverseProperty("CatalogItems")]
    public virtual Partition Partition { get; set; }
}