// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UNAHUR.IoT.DAL.MOdels;

[Table("Partitions", Schema = "common")]
[Index("PartitionLevel", Name = "IX_Partitions_PartitionLevel", IsUnique = true)]
public partial class Partition
{
    /// <summary>
    /// Unique identifier
    /// </summary>
    [Key]
    public int PartitionId { get; set; }

    /// <summary>
    /// Hieracy Id of the partition
    /// </summary>
    [Required]
    public HierarchyId PartitionLevel { get; set; }

    /// <summary>
    /// Name 
    /// </summary>
    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    /// <summary>
    /// Description
    /// </summary>
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    /// <summary>
    /// Last modified date
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime LastModified { get; set; }

    /// <summary>
    /// Last modification user
    /// </summary>
    [Required]
    [StringLength(128)]
    [Unicode(false)]
    public string LastModifiedBy { get; set; }

    [InverseProperty("Partition")]
    public virtual ICollection<CatalogItem> CatalogItems { get; set; } = new List<CatalogItem>();
}