// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using UNAHUR.IoT.DAL.Context.Configurations;
using UNAHUR.IoT.DAL.Models;
#nullable disable

namespace UNAHUR.IoT.DAL.Context;

public partial class IoTContext : DbContext
{
    public IoTContext(DbContextOptions<IoTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CatalogItem> CatalogItems { get; set; }

    public virtual DbSet<CatalogItemsInfo> CatalogItemsInfos { get; set; }

    public virtual DbSet<Partition> Partitions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.CatalogItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CatalogItemsInfoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PartitionConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
