// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UNAHUR.IoT.DAL.Context;
using UNAHUR.IoT.DAL.MOdels;

namespace UNAHUR.IoT.DAL.Context.Configurations
{
    public partial class CatalogItemsInfoConfiguration : IEntityTypeConfiguration<CatalogItemsInfo>
    {
        public void Configure(EntityTypeBuilder<CatalogItemsInfo> entity)
        {
            entity.ToView("CatalogItemsInfo", "common");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CatalogItemsInfo> entity);
    }
}
