// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using UNAHUR.IoT.DAL.Context;
using UNAHUR.IoT.DAL.MOdels;

namespace UNAHUR.IoT.DAL.Context.Configurations
{
    public partial class PartitionConfiguration : IEntityTypeConfiguration<Partition>
    {
        public void Configure(EntityTypeBuilder<Partition> entity)
        {
            entity.Property(e => e.PartitionId)
            .ValueGeneratedNever()
            .HasComment("Unique identifier");
            entity.Property(e => e.Description).HasComment("Description");
            entity.Property(e => e.LastModified)
            .HasDefaultValueSql("(getdate())")
            .HasComment("Last modified date");
            entity.Property(e => e.LastModifiedBy)
            .HasDefaultValueSql("(suser_sname())")
            .HasComment("Last modification user");
            entity.Property(e => e.Name).HasComment("Name ");
            entity.Property(e => e.PartitionLevel).HasComment("Hieracy Id of the partition");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Partition> entity);
    }
}
